# Generated by Django 5.2.6 on 2025-09-18 05:13

import apps.models.managers
import apps.models.users
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apps", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", apps.models.managers.CustomUserManager()),
            ],
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(
                max_length=20,
                unique=True,
            ),
        ),
    ]
